### ISSUE TITLE
Can't bookmark specific views as PWA on iOS 15.5

### ISSUE THREAD

**Issue by jbarbero** [200ok-ch/organice#897] opened 2022-09-05 04:32 UTC
**Describe the bug**
Can only bookmark the index.html view on iOS 15.5 Mobile Safari.

**To Reproduce**
1. Go to https://organice.200ok.ch/files/foobar in Mobile Safari on iOS 15.5
3. Click on Share -> Add to Home Screen
4. URL offered is https://organice.200ok.ch/index.html

**Expected behavior**
The URL offered should be: https://organice.200ok.ch/files/foobar

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: iOS 15.5
 - Browser: Safari

**Additional context**

I think the problem is that the manifest start_url is not being generated correctly here:
https://github.com/200ok-ch/organice/blame/master/public/index.html

I will try to debug this, but wanted to post the issue first.

Thanks!

**Comment by schoettl** [comment] 2022-09-05 19:40
Thanks for the report!

Can't test on iOS but on Android with Firefox, it works.

**Comment by jbarbero** [comment] 2022-09-06 00:33
I will try to run it myself and submit a fix when I have a moment.

**Comment by munen** [comment] 2022-09-15 09:29
I confirm that it does not work on iOS 15.6.1. It definitively used to work. And we had to adapt this once or twice already due to changes in iOS or Android. Not saying that it is not a regression on our side this time. I haven't looked into it, yet.

My old bookmark on the homescreen still works, though.

@jbarbero Thank you for the report :pray: 

> I will try to run it myself and submit a fix when I have a moment.

That is very kind of you! I'll assign the issue to you, then.

**Comment by munen** [comment] 2023-01-04 13:32
Bookmarking a specific view was something that we previously explicitly built, because it seemed like a good idea. It worked well for me in the last years (and it still works on my phone - probably because the bookmark is older than my phone).

For two reasons I've added a different issue which will fix this one:

1. Saving specific bookmarks seems to be brittle on both mobile platforms for whatever reason. Personally, I don't like these mobile platforms overriding basic web functionality, but it is what it is(;
2. Even if bookmarking a specific file would still work, it would be committing to this file to be your startup file.

Hence, I've opened a new issue https://github.com/200ok-ch/organice/issues/919 to enable the user to set a default file in the file settings. To me, this seems the way to go.

**Comment by munen** [comment] 2023-01-04 14:17
Long story short, I implemented #919 in #922.

It is my understanding that the implementation will solve your workflow request. If it's alright with both of you @jbarbero and @schoettl, we can close this issue.

**Comment by jbarbero** [comment] 2023-01-08 23:33
Hi Alain,

Thank you, that looks like a great fix. I would have preferred being able
to bookmark a subdirectory as well, but this is already very helpful!

Best,
János

**Comment by munen** [comment] 2023-01-09 08:06
Hi János

> Thank you, that looks like a great fix.

Thank you for the kind words🙏

> I would have preferred being able to bookmark a subdirectory as well, but this is already very helpful!

I understand. It's only been about two years that I've put substantial (research and a bit of coding) effort into making bookmarks work, again, on iOS and Android properly. And even before that it was an extra effort to get them to work in the first place. It seems like the iOS and Android APIs are really brittle concerning this basic web functionality.

If you're interested you can check it out and make bookmarks work independently of the change I've made. A little time ago, your requirement to bookmark a subdirectory would totally have worked.

Here are the two last PRs where we worked on this:

- https://github.com/200ok-ch/organice/pull/465
- A bit more background: https://github.com/200ok-ch/organice/pull/463

Kind regards,
Alain

**Comment by munen** [comment] 2023-01-09 08:10
Random hunch, but maybe this is related: https://github.com/200ok-ch/organice/issues/904

**Comment by munen** [comment] 2023-06-20 14:55
This issue is now superseded by #919 which is also implemented.

**Closed by munen** 2023-06-20 14:55 UTC
Labels: bug, question
