### ISSUE TITLE
`yarn test` fails on fresh install on mac

### ISSUE THREAD

**Issue by jzohrab** [200ok-ch/organice#705] opened 2021-06-23 03:03 UTC
**Describe the bug**

Running all tests as at commit `f999aeba31c257cc52c`

```
 FAIL  src/components/OrgFile/OrgFile.integration.test.js (30.213s)
  ● Render all views › Org Functionality › Renders everything starting from an Org file › TaskList › orders tasks for an Org file
```

detail:

```

    expect(received).toMatchSnapshot()

    Snapshot name: `Render all views Org Functionality Renders everything starting from an Org file TaskList orders tasks for an Org file 1`

    - Snapshot
    + Received

    @@ -35,11 +35,10 @@
            value=""
          />
        </div>
        <div
          class="task-list__headers-container"
    -     style="overflow: auto;"
        >
          <div
            class="agenda-day__container"
          >
            <div

      402 |           fireEvent.click(getByTitle('Show task list'));
      403 |           const drawerElem = getByTestId('drawer');
    > 404 |           expect(drawerElem).toMatchSnapshot();
          |                              ^
      405 |         });
      406 | 
      407 |         test('search in TaskList filters headers (by default only with todoKeywords)', () => {

      at Object.toMatchSnapshot (src/components/OrgFile/OrgFile.integration.test.js:404:30)

 › 1 snapshot failed.
Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or press `u` to update them.

Test Suites: 1 failed, 10 passed, 11 total
Tests:       1 failed, 381 passed, 382 total
Snapshots:   1 failed, 2 passed, 3 total
Time:        25.271s
Ran all test suites.
```

I re-ran all tests, this failed again.

If I re-run with just failed tests, that test still fails.

**Desktop (please complete the following information):**
 - Mac Catalina 10.15.7

LMK if any more detail needed.

I wanted to submit this before spending any time trying to solve the problem, perhaps the team's already aware.  Thank you!

**Comment by munen** [comment] 2021-07-11 10:14
Hi @jzohrab 

Thank you for bringing this up and apologies for the late response!

It's unfortunate that the tests do fail on a Mac. We haven't been aware of this, yet. The contributors mainly use Linux and Windows, I'm not sure if a Mac user has contributed yet. Having said so, there shouldn't be anything in the tests or organice that's platform specific and all contributors and users are very welcome!

Having said so, I'm afraid that your PR proposal unfortunately cannot be merged. The change fails on CI as it does on my machine. To me, it looks like this is not a bug within organice, but within the tooling that we use for tests. The reason is that the same test generates a slightly different DOM for Linux/Windows as for Mac. Chances are it's within [@testing-library/jest-dom](https://github.com/testing-library/jest-dom) that we use for DOM generation.

Let's try upgrading that and see if the issue persists. We currently use 5.11.4 whereas 5.14.1 is the newest available version.

**Comment by munen** [comment] 2021-07-11 10:22
I have bumped the versions of the libraries that might cause this (@testing-library/react and @testing-library/jest-dom) to the newest available versions. The tests still run fine on CI and on my machine.

Can you please retry running the tests on current `master` on your machine and give some feedback on whether the tests run now? :pray:

**Comment by jzohrab** [comment] 2021-07-11 21:37
Thanks, have updated, but I still get the same error.

```
$ git log -n 1
commit 4ceb7facfd0... (HEAD -> master, upstream/master, upstream/HEAD)
```

Details:

```
 FAIL  src/components/OrgFile/OrgFile.integration.test.js (23.792s)
  ● Render all views › Org Functionality › Renders everything starting from an Org file › TaskList › orders tasks for an Org file

    expect(received).toMatchSnapshot()

    Snapshot name: `Render all views Org Functionality Renders everything starting from an Org file TaskList orders tasks for an Org file 1`

    - Snapshot
    + Received

    @@ -35,11 +35,10 @@
            value=""
          />
        </div>
        <div
          class="task-list__headers-container"
    -     style="overflow: auto;"
        >
          <div
```

After `git pull` I ran the following:

```
nvm install
nvm use
yarn install --production=false
yarn test
```


fyi, after `yarn install ...` I get several error messages, but the build completes:

<details>
  <summary>Click to see build errors</summary>

```
22 warnings and 9 errors generated.
22make: *** [Release/obj.target/fse/fsevents.o] Error 1
 warnings and 9 errors generated.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/Users/jeff/.nvm/versions/node/v12.13.1/bin/node\" \"/Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/jeff/Documents/Projects/organice/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/jeff/Documents/Projects/organice/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=5\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/jeff/Documents/Projects/organice/node_modules/fsevents
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/jeff/.nvm/versions/node/v12.13.1/bin/node /Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jeff/Documents/Projects/organice/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/jeff/Documents/Projects/organice/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jeff/Documents/Projects/organice/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 19.6.0
node-pre-gyp ERR! command \"/Users/jeff/.nvm/versions/node/v12.13.1/bin/node\" \"/Users/jeff/Documents/Projects/organice/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/jeff/Documents/Projects/organice/node_modules/fsevents
node-pre-gyp ERR! node -v v12.13.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
Failed to execute '/Users/jeff/.nvm/versions/node/v12.13.1/bin/node /Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jeff/Documents/Projects/organice/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/jeff/Documents/Projects/organice/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/Users/jeff/.nvm/versions/node/v12.13.1/bin/node\" \"/Users/jeff/.nvm/versions/node/v12.13.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/jeff/Documents/Projects/organice/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/jeff/Documents/Projects/organice/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=5\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/jeff/Documents/Projects/organice/node_modules/fsevents
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok"
```

</details>

I have 

```
$ node --version
v12.13.1
```

Should I do anything else to fully refresh my environment?  Thanks! jz

**Comment by munen** [comment] 2021-07-14 18:36
The install errors all seem to be related to `fsevents`. That's a libarary to check for, well file system events(; That's only required to do hot reloading and auto-running tests on changes. It wouldn't introduce the DOM changes during the test runs.

Your Node version is also the right one as specified in `.nvmrc`.

Sometimes the hail mary is to `rm -rf node_modules` and re-install the dependencies with `yarn install --production=false`. 

In any case, I still cannot see how we can fix the error if Jest generates different DOMs on different machines. 

Possible actions are:

- Create an issue against Jest upstream: https://github.com/facebook/jest
- Ignore the error while developing, knowing that CI is green (not superly nice, but you could always comment the one test out).
- Use a Docker or VM dev environment.

Would any of that work for you?

**Comment by munen** [comment] 2022-06-21 13:49
Since this issue has been stale for a year, and none of the maintainers owns a Mac for further testing, I'll close it according to the [contributor guidelines](https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org).

If you want to work on this issue, please feel free re-open it any time! :pray:

**Closed by munen** 2022-06-21 13:49 UTC
Labels: bug, question
