### ISSUE TITLE
Org file clock are added by accident.

### ISSUE THREAD

**Issue by tru2dagame** [200ok-ch/organice#110] opened 2019-11-21 19:58 UTC
![image](https://user-images.githubusercontent.com/1673006/69372167-24ebe800-0cdc-11ea-845b-c9f0092604f8.png)

I found couple times, that organice would mess up the state and clock by accident.

**Comment by munen** [comment] 2019-11-21 20:49
Yes, that's a good catch! From memory, I can see why the parser did it.

Out of curiosity, how did you manage to get those ` - State "DONE"       from "TODO"       [2019-11-21 Thu 21:46]` statements within the `:LOGBOOK:` drawer? I only know them from schedules/deadlines in which they would get a separate drawer like this:

```
* TODO Header with schedule and clocked time
  SCHEDULED: <2019-11-22 Fri +1d>
  :PROPERTIES:
  :LAST_REPEAT: [2019-11-21 Thu 21:46]
  :END:
  
  - State "DONE"       from "TODO"       [2019-11-21 Thu 21:46]
  :LOGBOOK:
  CLOCK: [2019-11-12 Tue 14:15]--[2019-11-12 Tue 13:20] => -0:55
  CLOCK: [2019-11-12 Tue 14:15]--[2019-11-12 Tue 14:25] =>  0:10
  :END:
```

I'm assuming there's a configuration flag that'll make org track the toggled time and add it to the same drawer as the clocked time.

In any case, the parser will have to be hardened, here.

**Comment by tru2dagame** [comment] 2019-11-21 20:52
Hi @Linuus
I use C-c C-t d to make it done.
The emacs configuration I use is https://github.com/purcell/emacs.d

**Comment by tru2dagame** [comment] 2019-11-21 20:53
Hi @munen,
I use C-c C-t d to make it done.
The emacs configuration I use is https://github.com/purcell/emacs.d

**Comment by munen** [comment] 2019-11-21 20:58
What function does `C-c C-t d` call? You can find out with `C-h c C-c C-t` (`C-h c` will always give you the description to key presses).

By default `C-c C-t` already calls `org-todo` which toggles the state, so the `d` wouldn't be part of the command.

**Comment by tru2dagame** [comment] 2019-11-21 21:03
![image](https://user-images.githubusercontent.com/1673006/69376393-2b329200-0ce5-11ea-988b-fe72eb869f34.png)
It triggers `org-todo` then mark it `done`.

**Comment by tru2dagame** [comment] 2019-11-21 21:05
@munen 
I think it's this one: https://emacs.stackexchange.com/questions/47951/marking-a-todo-item-done-does-not-create-a-closing-timestamp-in-org-mode

> https://github.com/purcell/emacs.d/blob/master/lisp/init-org.el#L44

**Comment by munen** [comment] 2019-11-22 21:48
@tru2dagame This issue has been addressed in a PR #112  by @jamesnvc.

Could you please give it a go one more time and confirm that the issue is gone for you, too? Please make sure to empty the cache and reload organice beforehand.

**Comment by munen** [comment] 2019-11-23 17:15
> @munen I think it's this one:
> https://github.com/purcell/emacs.d/blob/master/lisp/init-org.el#L44
> 
> > https://www.gnu.org/software/emacs/manual/html_node/org/Closing-items.html
> > https://emacs.stackexchange.com/questions/47951/marking-a-todo-item-done-does-not-create-a-closing-timestamp-in-org-mode

Yes, that's the flag! Thanks for looking it up and getting back to me!🙏

It's a nice flag to have set. And with PR #112 organice should treat the data set correctly, too.

**Comment by tru2dagame** [comment] 2019-11-25 05:25
@munen yes, I tried playing with the latest version. It works without any issue. Thanks!

**Closed** 2019-11-25 05:25 UTC
Labels: bug

**Comment by munen** [comment] 2019-11-25 06:18
Perfect, thank you for testing! 🙏
