### ISSUE TITLE
Deployment under a URL subfolder

### ISSUE THREAD

**Issue by alethiophile** [200ok-ch/organice#732] opened 2021-10-16 22:23 UTC
**Describe the bug**
I'm trying to deploy Organice under a URL subfolder. There's a Nextcloud instance hosted on another subfolder of the same domain, and the goal is to be able to use Organice on those files without having to loosen the CORS settings. Having Organice hosted under the same subdomain should allow this due to same-origin (AFAICT).

However, it seems that Organice always assumes it will be hosted at the root of the subdomain. When I configure my server to host the Organice build directory at the URL subfolder `organice`, it successfully downloads the index.html, but all requests for static resources go to `/static/js/etc` directly, rather than `/organice/static/js/etc`. This makes organice fail to load.

I've tried adding a `homepage` directive to the `package.json`, as described in the Create React App docs [here](https://create-react-app.dev/docs/deployment#building-for-relative-paths). When I build with this set, organice loads successfully; however, for some reason, on first loading `index.html`, the client-side router redirects me to the root of the subdomain (rather than `/organice/`). How do I make it use the correct URLs on the client side?

**To Reproduce**
1. Configure your Web server to serve organice under a URL subdirectory e.g. `/organice/`
2. Watch it fail to load all the static assets

**Comment by munen** [comment] 2021-11-02 09:21
Relabeled, because this is a change request, not a bug in existing behaviour.

**Comment by munen** [comment] 2021-11-02 09:21
Hi @alethiophile 

Thank you for opening a new issue. Are you planning on working on this?

**Comment by munen** [comment] 2022-01-03 14:19
Closing this issue as per https://github.com/200ok-ch/organice/blob/master/CONTRIBUTING.org#how-we-work-with-issues. If you choose to work on it at some point later, please re-open the issue.

**Closed by munen** 2022-01-03 14:19 UTC
Labels: enhancement, question
