### ISSUE TITLE
Organice would be perfect with direct git(hub/lab) integration

### ISSUE THREAD

**Issue by forkrul** [200ok-ch/organice#484] opened 2020-09-25 06:09 UTC
Organice is a great tool. I'd like to use my existing org-mode git repos with it.

I'd like support for github/gitlab repos (similar to what logseq.com provides) natively in Organice.

I've not really considered alternatives, as Organice really is fully featured, and I don't trust Dropbox/Google with my data, and myself to maintain a Webdav server online. 

https://isomorphic-git.org/ might work as a possible solution.

**Comment by schoettl** [comment] 2020-09-25 07:13
Hi @forkrul, I think this is a duplicate of #279. Would you add your ideas and insights about isomorphic-git there, so that we have one place to work on this? I close this issue and re-open the other one.

**Closed by schoettl** 2020-09-25 07:13 UTC
