### ISSUE TITLE
Docs should use CUSTOM_ID permalinks everywhere

### ISSUE THREAD

**Issue by aspiers** [200ok-ch/organice#342] opened 2020-06-08 11:27 UTC
Currently the docs use a mixture of `<<radio targets>>` and `CUSTOM_ID` properties to allow deep-linking to particular sections.  The latter are much better because:

1. they provide a stable permalink which will not break when the docs are regenerated, e.g. compare https://organice.200ok.ch/documentation.html#deployment vs. https://organice.200ok.ch/documentation.html#orgc7ecd7e which is randomly generated each time
2. the permalink is human-readable
3. GitHub's rendering of the `.org` file results in radio targets polluting the text, whereas `CUSTOM_ID` anchors are nicely hidden.

So I propose switching all radio targets to `CUSTOM_ID` properties.

**Comment by munen** [comment] 2020-06-08 15:49
@aspiers I concur, having "reproducible links" would be great!

I've created a PR that replaces the radio targets with `CUSTOM_ID`s.

That only solves the problem of the polluted GH rendering. It won't fix the random anchors for the headers that don't have a `CUSTOM_ID`.

I checked the [docs](https://orgmode.org/manual/HTML-Export.html) if there's an option to generate a `CUSTOM_ID` off the header name, but couldn't find one. I think the relevant function for creating the anchor is `org-html--format-toc-headline` in `ox-html.el`.

Before I dig any further: Do you know of a an option to use `CUSTOM_ID`s everywhere without writing custom elisp code?

**Comment by aspiers** [comment] 2020-06-08 16:08
[**@munen**](https://github.com/munen) commented on [June 8, 2020 4:49 PM](https://github.com/200ok-ch/organice/issues/342#issuecomment-640713899 "2020-06-08T15:49:31Z - Replied by Github Reply Comments"):
> Before I dig any further: Do you know of a an option to use `CUSTOM_ID`s everywhere without writing custom elisp code?

Looks like https://thibaultmarin.github.io/blog/posts/2017-08-15-Personal_wiki_in_org.html#org8858f73 does it, I think?

**Comment by munen** [comment] 2020-06-14 16:37
>> Before I dig any further: Do you know of a an option to use `CUSTOM_ID`s everywhere without writing custom elisp code?

> Looks like https://thibaultmarin.github.io/blog/posts/2017-08-15-Personal_wiki_in_org.html#org8858f73 does it, I think?

*hihi*, yes that looks like an option that uses custom elisp code(;

Quoting: "This require the custom ™/org-element-title-lineage function (see here)."

But yeah, I'm fine with adding some nice elisp to the organice codebase!(;

**Comment by munen** [comment] 2020-07-15 08:42
Changing to label to `enhancement`, because I don't want to call out default Org export behavior as buggy(;

**Comment by aspiers** [comment] 2020-12-13 00:14
It seems that the Org community is currently debating whether it is buggy ;-) https://orgmode.org/list/CAJcAo8tXVW39h18FUXLtwoDYNKQsFHqCp+YDiyWfLee29B1PRw@mail.gmail.com/t/

**Comment by munen** [comment] 2020-12-13 11:01
*hihi*, if there’s an upstream change coming, that would be interesting. 

Ever since you’ve pointed me at this, I feel I’ve been writing CUSTOM_ID properties on a daily basis (for example also on PM docs that we share with customers). 

I’d be interested to see how they want to fix it. I don’t see how to do it without state or auto-generating the current properties. Personally, I’d be happy for the latter, every time I’m writing one I’m thinking that this would be a good time to write 2 lines of elisp and get it over with for the next time(;

**Comment by aspiers** [comment] 2020-12-13 11:18
Yes, this does look very promising! :sunglasses:

**Comment by munen** [comment] 2022-06-27 08:48
In the meantime, all `<<radio_targets>>` have been converted to `CUSTOM_ID`. Also, the links are not relative, but lead to Github, so that they work from Emacs, Github and organice.200ok.ch/documentation.html.

Thank you for reporting :pray:

**Closed by munen** 2022-06-27 08:48 UTC
Labels: enhancement
