### ISSUE TITLE
Ability to select the day a week starts with

### ISSUE THREAD

**Issue by fkohrt** [200ok-ch/organice#266] opened 2020-03-12 23:58 UTC
**Is your feature request related to a problem? Please describe.**
The agenda currently always starts the week on a Sunday.

**Describe the solution you'd like**
An option in the settings that let's the user choose on what day he wants the week to start.

**Comment by schoettl** [comment] 2020-03-13 10:09
That would be a nice feature. Can you work on this?

Otherwise, please see our contributing guidelines. Unless someone commits to work on the issue, we will close it because it's not a bug.

**Comment by schoettl** [comment] 2020-03-13 22:01
You can re-open the issue if you have time to work on it. But we want to keep the number of issues manageable.

**Closed by schoettl** 2020-03-13 22:01 UTC

**Comment by munen** [comment] 2020-03-14 17:39
:+1:
